//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderDetails
    {
        public int ProviderId { get; set; }
        public string OrganisationName { get; set; }
        public long Contact { get; set; }
    }
}
