//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTickets
    {
        public int TicketId { get; set; }
        public int UserId { get; set; }
    
        public virtual UserDetails UserDetails { get; set; }
    }
}
