//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusReservation.ClientServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCityDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetCityDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityState {
            get {
                return this.CityStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CityStateField, value) != true)) {
                    this.CityStateField = value;
                    this.RaisePropertyChanged("CityState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRouteDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetRouteDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RouteIdField;
        
        private int BusIdField;
        
        private int SourceIdField;
        
        private int DestinationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfJourneyField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNoField;
        
        private System.Nullable<double> RatingField;
        
        private System.Nullable<int> AvailableSeatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DestinationId {
            get {
                return this.DestinationIdField;
            }
            set {
                if ((this.DestinationIdField.Equals(value) != true)) {
                    this.DestinationIdField = value;
                    this.RaisePropertyChanged("DestinationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DateOfJourney {
            get {
                return this.DateOfJourneyField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfJourneyField, value) != true)) {
                    this.DateOfJourneyField = value;
                    this.RaisePropertyChanged("DateOfJourney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalTimeField, value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTimeField, value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BusName {
            get {
                return this.BusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNameField, value) != true)) {
                    this.BusNameField = value;
                    this.RaisePropertyChanged("BusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string BusNo {
            get {
                return this.BusNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNoField, value) != true)) {
                    this.BusNoField = value;
                    this.RaisePropertyChanged("BusNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<double> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> AvailableSeats {
            get {
                return this.AvailableSeatsField;
            }
            set {
                if ((this.AvailableSeatsField.Equals(value) != true)) {
                    this.AvailableSeatsField = value;
                    this.RaisePropertyChanged("AvailableSeats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBookingStatus_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetBookingStatus_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BusIdField;
        
        private int SeatNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SeatNo {
            get {
                return this.SeatNoField;
            }
            set {
                if ((this.SeatNoField.Equals(value) != true)) {
                    this.SeatNoField = value;
                    this.RaisePropertyChanged("SeatNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SeatType {
            get {
                return this.SeatTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatTypeField, value) != true)) {
                    this.SeatTypeField = value;
                    this.RaisePropertyChanged("SeatType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPassangerDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetPassangerDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PassengerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private int TicketIdField;
        
        private int SeatNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PassengerId {
            get {
                return this.PassengerIdField;
            }
            set {
                if ((this.PassengerIdField.Equals(value) != true)) {
                    this.PassengerIdField = value;
                    this.RaisePropertyChanged("PassengerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TicketId {
            get {
                return this.TicketIdField;
            }
            set {
                if ((this.TicketIdField.Equals(value) != true)) {
                    this.TicketIdField = value;
                    this.RaisePropertyChanged("TicketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SeatNo {
            get {
                return this.SeatNoField;
            }
            set {
                if ((this.SeatNoField.Equals(value) != true)) {
                    this.SeatNoField = value;
                    this.RaisePropertyChanged("SeatNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRouteDetailById_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetRouteDetailById_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RouteIdField;
        
        private int BusIdField;
        
        private int SourceIdField;
        
        private int DestinationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfJourneyField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DestinationId {
            get {
                return this.DestinationIdField;
            }
            set {
                if ((this.DestinationIdField.Equals(value) != true)) {
                    this.DestinationIdField = value;
                    this.RaisePropertyChanged("DestinationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DateOfJourney {
            get {
                return this.DateOfJourneyField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfJourneyField, value) != true)) {
                    this.DateOfJourneyField = value;
                    this.RaisePropertyChanged("DateOfJourney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalTimeField, value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTimeField, value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServiceReference.ClientWebServiceSoap")]
    public interface ClientWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BusReservation.ClientServiceReference.HelloWorldResponse HelloWorld(BusReservation.ClientServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.HelloWorldResponse> HelloWorldAsync(BusReservation.ClientServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetCityDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityDetails", ReplyAction="*")]
        BusReservation.ClientServiceReference.GetCityDetailsResponse GetCityDetails(BusReservation.ClientServiceReference.GetCityDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetCityDetailsResponse> GetCityDetailsAsync(BusReservation.ClientServiceReference.GetCityDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetRouteDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteDetails", ReplyAction="*")]
        BusReservation.ClientServiceReference.GetRouteDetailsResponse GetRouteDetails(BusReservation.ClientServiceReference.GetRouteDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetRouteDetailsResponse> GetRouteDetailsAsync(BusReservation.ClientServiceReference.GetRouteDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetBookingStatusesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookingStatuses", ReplyAction="*")]
        BusReservation.ClientServiceReference.GetBookingStatusesResponse GetBookingStatuses(BusReservation.ClientServiceReference.GetBookingStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookingStatuses", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetBookingStatusesResponse> GetBookingStatusesAsync(BusReservation.ClientServiceReference.GetBookingStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookTicket", ReplyAction="*")]
        bool BookTicket(int seatNo, int busId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> BookTicketAsync(int seatNo, int busId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTicketDetails", ReplyAction="*")]
        bool AddTicketDetails(int routeId, int totalNumberOfSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTicketDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddTicketDetailsAsync(int routeId, int totalNumberOfSeats);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPassanger", ReplyAction="*")]
        BusReservation.ClientServiceReference.AddPassangerResponse AddPassanger(BusReservation.ClientServiceReference.AddPassangerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPassanger", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.AddPassangerResponse> AddPassangerAsync(BusReservation.ClientServiceReference.AddPassangerRequest request);
        
        // CODEGEN: Generating message contract since element name GetPassengerDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPassengerDetails", ReplyAction="*")]
        BusReservation.ClientServiceReference.GetPassengerDetailsResponse GetPassengerDetails(BusReservation.ClientServiceReference.GetPassengerDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPassengerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetPassengerDetailsResponse> GetPassengerDetailsAsync(BusReservation.ClientServiceReference.GetPassengerDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetRouteByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteById", ReplyAction="*")]
        BusReservation.ClientServiceReference.GetRouteByIdResponse GetRouteById(BusReservation.ClientServiceReference.GetRouteByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteById", ReplyAction="*")]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetRouteByIdResponse> GetRouteByIdAsync(BusReservation.ClientServiceReference.GetRouteByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BusReservation.ClientServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BusReservation.ClientServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetCityDetailsRequestBody Body;
        
        public GetCityDetailsRequest() {
        }
        
        public GetCityDetailsRequest(BusReservation.ClientServiceReference.GetCityDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCityDetailsRequestBody {
        
        public GetCityDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetCityDetailsResponseBody Body;
        
        public GetCityDetailsResponse() {
        }
        
        public GetCityDetailsResponse(BusReservation.ClientServiceReference.GetCityDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusReservation.ClientServiceReference.GetCityDetails_Result[] GetCityDetailsResult;
        
        public GetCityDetailsResponseBody() {
        }
        
        public GetCityDetailsResponseBody(BusReservation.ClientServiceReference.GetCityDetails_Result[] GetCityDetailsResult) {
            this.GetCityDetailsResult = GetCityDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetRouteDetailsRequestBody Body;
        
        public GetRouteDetailsRequest() {
        }
        
        public GetRouteDetailsRequest(BusReservation.ClientServiceReference.GetRouteDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sourceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int destinationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dateOfJourney;
        
        public GetRouteDetailsRequestBody() {
        }
        
        public GetRouteDetailsRequestBody(int sourceId, int destinationId, System.DateTime dateOfJourney) {
            this.sourceId = sourceId;
            this.destinationId = destinationId;
            this.dateOfJourney = dateOfJourney;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetRouteDetailsResponseBody Body;
        
        public GetRouteDetailsResponse() {
        }
        
        public GetRouteDetailsResponse(BusReservation.ClientServiceReference.GetRouteDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusReservation.ClientServiceReference.GetRouteDetails_Result[] GetRouteDetailsResult;
        
        public GetRouteDetailsResponseBody() {
        }
        
        public GetRouteDetailsResponseBody(BusReservation.ClientServiceReference.GetRouteDetails_Result[] GetRouteDetailsResult) {
            this.GetRouteDetailsResult = GetRouteDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingStatusesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingStatuses", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetBookingStatusesRequestBody Body;
        
        public GetBookingStatusesRequest() {
        }
        
        public GetBookingStatusesRequest(BusReservation.ClientServiceReference.GetBookingStatusesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookingStatusesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int busId;
        
        public GetBookingStatusesRequestBody() {
        }
        
        public GetBookingStatusesRequestBody(int busId) {
            this.busId = busId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingStatusesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingStatusesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetBookingStatusesResponseBody Body;
        
        public GetBookingStatusesResponse() {
        }
        
        public GetBookingStatusesResponse(BusReservation.ClientServiceReference.GetBookingStatusesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookingStatusesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusReservation.ClientServiceReference.GetBookingStatus_Result[] GetBookingStatusesResult;
        
        public GetBookingStatusesResponseBody() {
        }
        
        public GetBookingStatusesResponseBody(BusReservation.ClientServiceReference.GetBookingStatus_Result[] GetBookingStatusesResult) {
            this.GetBookingStatusesResult = GetBookingStatusesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPassangerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPassanger", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.AddPassangerRequestBody Body;
        
        public AddPassangerRequest() {
        }
        
        public AddPassangerRequest(BusReservation.ClientServiceReference.AddPassangerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPassangerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string number;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int seatNo;
        
        public AddPassangerRequestBody() {
        }
        
        public AddPassangerRequestBody(string name, int age, string gender, string number, int seatNo) {
            this.name = name;
            this.age = age;
            this.gender = gender;
            this.number = number;
            this.seatNo = seatNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPassangerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPassangerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.AddPassangerResponseBody Body;
        
        public AddPassangerResponse() {
        }
        
        public AddPassangerResponse(BusReservation.ClientServiceReference.AddPassangerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPassangerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddPassangerResult;
        
        public AddPassangerResponseBody() {
        }
        
        public AddPassangerResponseBody(bool AddPassangerResult) {
            this.AddPassangerResult = AddPassangerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPassengerDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPassengerDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetPassengerDetailsRequestBody Body;
        
        public GetPassengerDetailsRequest() {
        }
        
        public GetPassengerDetailsRequest(BusReservation.ClientServiceReference.GetPassengerDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPassengerDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ticketId;
        
        public GetPassengerDetailsRequestBody() {
        }
        
        public GetPassengerDetailsRequestBody(int ticketId) {
            this.ticketId = ticketId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPassengerDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPassengerDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetPassengerDetailsResponseBody Body;
        
        public GetPassengerDetailsResponse() {
        }
        
        public GetPassengerDetailsResponse(BusReservation.ClientServiceReference.GetPassengerDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPassengerDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusReservation.ClientServiceReference.GetPassangerDetails_Result[] GetPassengerDetailsResult;
        
        public GetPassengerDetailsResponseBody() {
        }
        
        public GetPassengerDetailsResponseBody(BusReservation.ClientServiceReference.GetPassangerDetails_Result[] GetPassengerDetailsResult) {
            this.GetPassengerDetailsResult = GetPassengerDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteById", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetRouteByIdRequestBody Body;
        
        public GetRouteByIdRequest() {
        }
        
        public GetRouteByIdRequest(BusReservation.ClientServiceReference.GetRouteByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRouteByIdRequestBody() {
        }
        
        public GetRouteByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusReservation.ClientServiceReference.GetRouteByIdResponseBody Body;
        
        public GetRouteByIdResponse() {
        }
        
        public GetRouteByIdResponse(BusReservation.ClientServiceReference.GetRouteByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusReservation.ClientServiceReference.GetRouteDetailById_Result[] GetRouteByIdResult;
        
        public GetRouteByIdResponseBody() {
        }
        
        public GetRouteByIdResponseBody(BusReservation.ClientServiceReference.GetRouteDetailById_Result[] GetRouteByIdResult) {
            this.GetRouteByIdResult = GetRouteByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientWebServiceSoapChannel : BusReservation.ClientServiceReference.ClientWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientWebServiceSoapClient : System.ServiceModel.ClientBase<BusReservation.ClientServiceReference.ClientWebServiceSoap>, BusReservation.ClientServiceReference.ClientWebServiceSoap {
        
        public ClientWebServiceSoapClient() {
        }
        
        public ClientWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.HelloWorldResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.HelloWorld(BusReservation.ClientServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BusReservation.ClientServiceReference.HelloWorldRequest inValue = new BusReservation.ClientServiceReference.HelloWorldRequest();
            inValue.Body = new BusReservation.ClientServiceReference.HelloWorldRequestBody();
            BusReservation.ClientServiceReference.HelloWorldResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.HelloWorldResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.HelloWorldAsync(BusReservation.ClientServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.HelloWorldResponse> HelloWorldAsync() {
            BusReservation.ClientServiceReference.HelloWorldRequest inValue = new BusReservation.ClientServiceReference.HelloWorldRequest();
            inValue.Body = new BusReservation.ClientServiceReference.HelloWorldRequestBody();
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.GetCityDetailsResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.GetCityDetails(BusReservation.ClientServiceReference.GetCityDetailsRequest request) {
            return base.Channel.GetCityDetails(request);
        }
        
        public BusReservation.ClientServiceReference.GetCityDetails_Result[] GetCityDetails() {
            BusReservation.ClientServiceReference.GetCityDetailsRequest inValue = new BusReservation.ClientServiceReference.GetCityDetailsRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetCityDetailsRequestBody();
            BusReservation.ClientServiceReference.GetCityDetailsResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetCityDetails(inValue);
            return retVal.Body.GetCityDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetCityDetailsResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.GetCityDetailsAsync(BusReservation.ClientServiceReference.GetCityDetailsRequest request) {
            return base.Channel.GetCityDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetCityDetailsResponse> GetCityDetailsAsync() {
            BusReservation.ClientServiceReference.GetCityDetailsRequest inValue = new BusReservation.ClientServiceReference.GetCityDetailsRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetCityDetailsRequestBody();
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetCityDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.GetRouteDetailsResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.GetRouteDetails(BusReservation.ClientServiceReference.GetRouteDetailsRequest request) {
            return base.Channel.GetRouteDetails(request);
        }
        
        public BusReservation.ClientServiceReference.GetRouteDetails_Result[] GetRouteDetails(int sourceId, int destinationId, System.DateTime dateOfJourney) {
            BusReservation.ClientServiceReference.GetRouteDetailsRequest inValue = new BusReservation.ClientServiceReference.GetRouteDetailsRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetRouteDetailsRequestBody();
            inValue.Body.sourceId = sourceId;
            inValue.Body.destinationId = destinationId;
            inValue.Body.dateOfJourney = dateOfJourney;
            BusReservation.ClientServiceReference.GetRouteDetailsResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetRouteDetails(inValue);
            return retVal.Body.GetRouteDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetRouteDetailsResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.GetRouteDetailsAsync(BusReservation.ClientServiceReference.GetRouteDetailsRequest request) {
            return base.Channel.GetRouteDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetRouteDetailsResponse> GetRouteDetailsAsync(int sourceId, int destinationId, System.DateTime dateOfJourney) {
            BusReservation.ClientServiceReference.GetRouteDetailsRequest inValue = new BusReservation.ClientServiceReference.GetRouteDetailsRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetRouteDetailsRequestBody();
            inValue.Body.sourceId = sourceId;
            inValue.Body.destinationId = destinationId;
            inValue.Body.dateOfJourney = dateOfJourney;
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetRouteDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.GetBookingStatusesResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.GetBookingStatuses(BusReservation.ClientServiceReference.GetBookingStatusesRequest request) {
            return base.Channel.GetBookingStatuses(request);
        }
        
        public BusReservation.ClientServiceReference.GetBookingStatus_Result[] GetBookingStatuses(int busId) {
            BusReservation.ClientServiceReference.GetBookingStatusesRequest inValue = new BusReservation.ClientServiceReference.GetBookingStatusesRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetBookingStatusesRequestBody();
            inValue.Body.busId = busId;
            BusReservation.ClientServiceReference.GetBookingStatusesResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetBookingStatuses(inValue);
            return retVal.Body.GetBookingStatusesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetBookingStatusesResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.GetBookingStatusesAsync(BusReservation.ClientServiceReference.GetBookingStatusesRequest request) {
            return base.Channel.GetBookingStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetBookingStatusesResponse> GetBookingStatusesAsync(int busId) {
            BusReservation.ClientServiceReference.GetBookingStatusesRequest inValue = new BusReservation.ClientServiceReference.GetBookingStatusesRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetBookingStatusesRequestBody();
            inValue.Body.busId = busId;
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetBookingStatusesAsync(inValue);
        }
        
        public bool BookTicket(int seatNo, int busId) {
            return base.Channel.BookTicket(seatNo, busId);
        }
        
        public System.Threading.Tasks.Task<bool> BookTicketAsync(int seatNo, int busId) {
            return base.Channel.BookTicketAsync(seatNo, busId);
        }
        
        public bool AddTicketDetails(int routeId, int totalNumberOfSeats) {
            return base.Channel.AddTicketDetails(routeId, totalNumberOfSeats);
        }
        
        public System.Threading.Tasks.Task<bool> AddTicketDetailsAsync(int routeId, int totalNumberOfSeats) {
            return base.Channel.AddTicketDetailsAsync(routeId, totalNumberOfSeats);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.AddPassangerResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.AddPassanger(BusReservation.ClientServiceReference.AddPassangerRequest request) {
            return base.Channel.AddPassanger(request);
        }
        
        public bool AddPassanger(string name, int age, string gender, string number, int seatNo) {
            BusReservation.ClientServiceReference.AddPassangerRequest inValue = new BusReservation.ClientServiceReference.AddPassangerRequest();
            inValue.Body = new BusReservation.ClientServiceReference.AddPassangerRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.number = number;
            inValue.Body.seatNo = seatNo;
            BusReservation.ClientServiceReference.AddPassangerResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).AddPassanger(inValue);
            return retVal.Body.AddPassangerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.AddPassangerResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.AddPassangerAsync(BusReservation.ClientServiceReference.AddPassangerRequest request) {
            return base.Channel.AddPassangerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.AddPassangerResponse> AddPassangerAsync(string name, int age, string gender, string number, int seatNo) {
            BusReservation.ClientServiceReference.AddPassangerRequest inValue = new BusReservation.ClientServiceReference.AddPassangerRequest();
            inValue.Body = new BusReservation.ClientServiceReference.AddPassangerRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.number = number;
            inValue.Body.seatNo = seatNo;
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).AddPassangerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.GetPassengerDetailsResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.GetPassengerDetails(BusReservation.ClientServiceReference.GetPassengerDetailsRequest request) {
            return base.Channel.GetPassengerDetails(request);
        }
        
        public BusReservation.ClientServiceReference.GetPassangerDetails_Result[] GetPassengerDetails(int ticketId) {
            BusReservation.ClientServiceReference.GetPassengerDetailsRequest inValue = new BusReservation.ClientServiceReference.GetPassengerDetailsRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetPassengerDetailsRequestBody();
            inValue.Body.ticketId = ticketId;
            BusReservation.ClientServiceReference.GetPassengerDetailsResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetPassengerDetails(inValue);
            return retVal.Body.GetPassengerDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetPassengerDetailsResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.GetPassengerDetailsAsync(BusReservation.ClientServiceReference.GetPassengerDetailsRequest request) {
            return base.Channel.GetPassengerDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetPassengerDetailsResponse> GetPassengerDetailsAsync(int ticketId) {
            BusReservation.ClientServiceReference.GetPassengerDetailsRequest inValue = new BusReservation.ClientServiceReference.GetPassengerDetailsRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetPassengerDetailsRequestBody();
            inValue.Body.ticketId = ticketId;
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetPassengerDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusReservation.ClientServiceReference.GetRouteByIdResponse BusReservation.ClientServiceReference.ClientWebServiceSoap.GetRouteById(BusReservation.ClientServiceReference.GetRouteByIdRequest request) {
            return base.Channel.GetRouteById(request);
        }
        
        public BusReservation.ClientServiceReference.GetRouteDetailById_Result[] GetRouteById(int id) {
            BusReservation.ClientServiceReference.GetRouteByIdRequest inValue = new BusReservation.ClientServiceReference.GetRouteByIdRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetRouteByIdRequestBody();
            inValue.Body.id = id;
            BusReservation.ClientServiceReference.GetRouteByIdResponse retVal = ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetRouteById(inValue);
            return retVal.Body.GetRouteByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetRouteByIdResponse> BusReservation.ClientServiceReference.ClientWebServiceSoap.GetRouteByIdAsync(BusReservation.ClientServiceReference.GetRouteByIdRequest request) {
            return base.Channel.GetRouteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusReservation.ClientServiceReference.GetRouteByIdResponse> GetRouteByIdAsync(int id) {
            BusReservation.ClientServiceReference.GetRouteByIdRequest inValue = new BusReservation.ClientServiceReference.GetRouteByIdRequest();
            inValue.Body = new BusReservation.ClientServiceReference.GetRouteByIdRequestBody();
            inValue.Body.id = id;
            return ((BusReservation.ClientServiceReference.ClientWebServiceSoap)(this)).GetRouteByIdAsync(inValue);
        }
    }
}
